version: "3.8"
services:
  traplogger:
    container_name: TrapLogger
    build: .
    environment:
      #SMTP details for email alerts
      SMTP_HOST: #smtp.example.com
      SMTP_PORT: #587
      SMTP_USERNAME: #user@example.com
      SMTP_PASSWORD: #your_password
      SMTP_USE_TLS: #"true"
      # EMAIL details
      EMAIL_FROM: #alerts@example.com
      EMAIL_TO: #helpdesk@example.com
    ports:
      # Comment/un-comment the port lines below to disable/enable the services you are using
      # FTP
      #- "21:21"
      # SSH
      # - "22:22"
      # Telnet
      # - "23:23"
      # TFTP
      # - "69:69"
      # HTTP
      - "898:80"
      # NTP
      # - "123:123"
      # SNMP
      # - "161:161"
      # MSSQL
      # - "1433:1433"
      # MYSQL
      # - "3306:3306"
      # RDP
      # - "3389:3389"
      # VNC
      # - "5000:5000"
      # SIP
      # - "5060:5060"
      # REDIS
      # - "6379:6379"
      # TCP Banner
      # - "8001:8001"
      # HTTP Proxy
      # - "8080:8080"
      # Git
      # - "9418:9418"
    volumes:
      - opencanary-logs:/var/log/opencanary # Mount for OpenCanary logs

volumes:
  opencanary-logs:
    driver: local
